project:
  name: connect-integration-webtext
  owner: support@webtext.com
  package_lambda: false
  regions:
  - us-east-1
  s3_bucket: ''
tests:
  defaults:
    parameters: {}
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/webtext.template.yaml
